name: aws-parallel-cluster
channels:
  - conda-forge
dependencies:
  - python=3
#aws
  - boto3
  - awscli
# gaass-py
  - pandas
  - numpy
  - rasterio
  - matplotlib
  - geopandas
  - shapely
  - scikit-learn
  - scikit-image
  - pipe
  - tqdm
  - geojson
# plotting
  - plotly
  - holoviews
  - geoviews
  - hvplot
  - datashader
  - panel
  - seaborn
  - cartopy
# stac VERSIONS are Important Here - bummer!
  - rioxarray
  - pystac
  - pystac-client
    # - pystac=1.1.0
    # - pystac-client=0.3.0
# CPU
  - psutil
  - scalene
  - yaml
  - python-ldap
    #- pyan3=1.1.1
# PIP Things
  - pip
  - pip:
    - pyan3==1.1.1
    - loguru
    - python-dotenv
    - aws-parallelcluster==3.7.0


