cat:
	cat Makefile


node:
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
	chmod ug+x ~/.nvm/nvm.sh
	source ~/.nvm/nvm.sh

#logout and nback in manually run nvm install 17

node2:
	#nvm install --lts
	echo nvm install 17
	node --version
